In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

# Create the dataset
data = {
    'age': [28, 27, 50, 60, 30, 32, 24, 29, 43, 43, 53, 63, 36, 48],
    'sex': ['female', 'male', 'female', 'male', 'female', 'male', 'female', 'male', 'female', 'male', 'female', 'male', 'female', 'male'],
    'bmi': [17.29, 18.905, 28.12, 33.11, 28.38, 28.12, 30.21, 22.515, 25.08, 27.36, 28.1, 33.66, 22.6, 28],
    'children': [0, 3, 3, 3, 1, 4, 3, 3, 0, 3, 3, 3, 2, 1],
    'smoker': ['no', 'no', 'no', 'no', 'yes', 'yes', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes'],
    'region': ['northeast', 'northeast', 'northwest', 'southeast', 'southeast', 'northwest', 'northwest', 'northeast', 'northeast', 'northeast', 'southwest', 'southeast', 'southwest', 'southwest'],
    'true_charges': [3732, 4828, 11085, 13919, 19521, 21472, 4618, 5209, 7325, 8606, 11741, 15161, 18608, 23568]
}

# Create DataFrame
df = pd.DataFrame(data)

# Preprocess categorical variables: encode 'sex' and 'smoker'
label_encoder_sex = LabelEncoder()
label_encoder_smoker = LabelEncoder()

df['sex_encoded'] = label_encoder_sex.fit_transform(df['sex'])  # female=0, male=1
df['smoker_encoded'] = label_encoder_smoker.fit_transform(df['smoker'])  # no=0, yes=1

# Define predictors (X) and target (y)
X = df[['age', 'sex_encoded', 'bmi', 'smoker_encoded']]
y = df['true_charges']

# Initialize and train the linear regression model
model = LinearRegression()
model.fit(X, y)

# Predict true_charges for all records
df['predicted_charges'] = model.predict(X)

# Select relevant columns to display
result_df = df[['age', 'sex', 'bmi', 'smoker', 'true_charges', 'predicted_charges']]

# Print the DataFrame with true and predicted charges
result_df

    age     sex     bmi smoker  true_charges  predicted_charges
0    28  female  17.290     no          3732        3424.543609
1    27    male  18.905     no          4828        4310.533781
2    50  female  28.120     no         11085       10291.555233
3    60    male  33.110     no         13919       14221.813948
4    30  female  28.380    yes         19521       19282.096256
5    32    male  28.120    yes         21472       20464.961538
6    24  female  30.210     no          4618        5016.873043
7    29    male  22.515     no          5209        5435.751074
8    43  female  25.080     no          7325        8184.045492
9    43    male  27.360     no          8606        9415.129366
10   53  female  28.100     no         11741       10942.369134
11   63    male  33.660     no         15161       14981.385321
12   36  female  22.600    yes         18608       19488.517232
13   48    male  28.000    yes         23568       23933.424974